name: Clean Install and Build Front and Back Ends
on:
  pull_request:
    branches:
      - preproduction
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Clean Install Backend Packages
        run: | 
          cd server
          npm ci

      - name: Build Backend
        run: |
          cd server
          npm run build
      
      - name: Clean Install Frontend Packages
        run: |
          cd client
          npm ci
      
      - name: Build Frontend
        run: |
          cd client
          npm run build

name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd client
          npm install
          npm run build
      - name: Firebase Deploy
        run: |
          cd client
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
