name: Install and Build
on:
  pull_request:
    branches:
      - preproduction
      - master
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install NPM Packages
        run: npm install

      - name: Build
        run: npm run build
